name: Update Profile README with Contributions

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SHACONT_TOKEN }}
          base: repositories
          plugin_repositories: yes
